### ISSUE TITLE
A review

### ISSUE THREAD

**Issue by aleos-dev** [anton-kulakov/CurrencyExchange#1]
### 1. ModelMapper Not Declared as Static
[CurrencyDAO.java Line 17](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L17)  
Why didn’t you declare modelMapper as static? Since it doesn’t hold any state, making it static would reduce memory usage by sharing a single instance across all usages.

### 2. DAO Directly Binding to DTO
[CurrencyDAO.java Line 59](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L59)  
You are binding the DAO directly to the DTO. The DAO should be dealing with entities, which are the internal representation of data in your application. The mapping from entities to DTOs should be done at a higher layer. The DAO should remain isolated and unaware of how the data is used by the application. 

Additionally, if block can be simplified using:
```java
Optional.ofNullable(currency)
    .map(currency -> modelMapper.map(currency, CurrencyDTO.class));
```
### 3. LinkedList Usage
[CurrencyDAO.java Line 72](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L72)  
There’s no benefit to using LinkedList here unless you need stack or queue behavior. While it doesn’t negatively impact performance in this specific case, it's better to use ArrayList in such scenarios because it offers better random access and is generally more efficient for most list operations.

### 4. Exception Handling
[CurrencyDAO.java Line 64](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L64)  
It’s good that you’ve introduced a general exception for the DB layer. However, adding meaningful descriptions to your exceptions is crucial. This will save you time when debugging and provide more context on what went wrong. It’s a great habit that can make debugging much easier down the road.

### 5. Manual Transaction Management
[ExchangeRateDAO.java Line 53](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/ExchangeRateDAO.java#L53)  
In a method like this, you should implement manual transaction management. You are making three separate database calls, which could lead to issues with data consistency and integrity. Wrapping these calls in a transaction ensures that either all operations succeed or none of them do, preventing partial updates. Additionally, you could fetch both currencies in a single query to reduce the number of database calls.

### 6. Service Layer for DAO Interactions
[ExchangeRateDAO.java Line 57](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/ExchangeRateDAO.java#L57)  
Instead of having ExchangeRateDAO directly depend on CurrencyDAO, consider creating a service class that interacts with both DAOs. The service class would manage the logic of fetching currencies and saving exchange rates, allowing the DAOs to remain focused purely on database operations. This approach would reduce coupling between DAOs and keep them more modular.

---
The main issue with the DAO layer is that it contains too much logic that doesn’t belong there. DAOs should focus solely on database operations (CRUD), and any other logic, such as mapping between entities and DTOs, should be handled at higher layers of the application. Keeping the DAO layer clean and isolated will make the codebase easier to maintain and test.

## Exception
[DBException.java Line 5](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/exception/DBException.java#L5)

This approach to using exceptions is somewhat unique, but it's not typical or recommended. The exception itself shouldn't define the response that is sent to the client; its main role is to provide information about what went wrong. It’s the responsibility of the handler to decide how to interpret that information and what response (such as HTTP status codes or error messages) should be returned to the client.

By placing the decision-making logic (like setting response codes) inside the exception itself, you risk tightly coupling the exception to the specific context of client responses, which reduces flexibility. While you can do this, it’s generally not worth it because it limits the reusability of the exception and breaks the separation of concerns. The exception should serve as a signal for what went wrong, and the handler should take care of the client-facing response.

Additionally, this is a checked exception, which means you are forced to propagate it explicitly through every method that might throw it. This can result in verbose code and unnecessary complexity. You could avoid this by extending from an unchecked exception (such as RuntimeException), which would allow you to propagate the exception naturally without requiring explicit throws declarations in every method signature.

In short, exceptions should provide internal information for handling errors, not dictate how those errors should be communicated to the client. It's better to use unchecked exceptions, which can simplify the flow and reduce boilerplate code.

## Service layer

Sometimes, using Optional.map() allows you to replace if statements and null checks, simplifying the code. 
[This logic can be replaced with next approach](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/service/ExchangeService.java#L33)

```java
return getOptionalExchangeRate(exchangeReqDTO).map(exchangeRate -> {
...
}
```
[This logic can be replaced with next approach](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/service/ExchangeService.java#L82)

```java
return exchangeRateDAO.getByCodes(reversedRateReq)
            .map(reversedRate -> {
                BigDecimal reversedRateValue = BigDecimal.ONE.divide(reversedRate.getRate(), 6, RoundingMode.HALF_UP);
                return exchangeRateDAO.save(new ExchangeRateReqDTO(exchangeReqDTO.getFrom(), exchangeReqDTO.getTo(), reversedRateValue)).orElse(null);
            });
```

## Data source
[Connection Manager](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/utils/ConnectionManager.java#L10)

Your approach resembles Dependency Injection (DI) since you initialize the datasource in a listener and set it as a dependency via a setter. However, by doing this, you violate the encapsulation of the ConnectionManager class. A better solution would be to initialize the datasource within a static block, ensuring it’s initialized when the class is loaded, thus maintaining encapsulation.

```java
static {
        currencyCodes = Currency.getAvailableCurrencies()
                .stream()
                .map(Currency::getCurrencyCode)
                .collect(Collectors.toSet());
    }

public static boolean isCurrencyCodeFollowStandard(String code) {
    return currencyCodes.contains(code);
}
```

Additionally, it's a best practice for utility classes to throw an exception in the constructor to prevent instantiation, including through reflection.

### AbstractMainController

[Exception Handling](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/AbstractMainController.java#L84)

The identical exception handling blocks in multiple methods don't look good. Whenever you notice repetitive code, it's a sign that something should be improved.

Since the request is processed by the service method before reaching the controller methods like doGet, doPost, etc., any exception thrown in these methods can be caught directly in the service method. This allows you to eliminate the redundancy of exception handling in every method and centralize it in the service method, making the code cleaner 

[Currency codes initialization](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/AbstractMainController.java#L117)
Calling this static method for initialization can cause issues in a multi-threaded environment, where multiple threads might try to initialize the resource at the same time. To avoid this, you should use a static block or implement double-checked locking. The better approach is to use a static block, as it guarantees thread-safe initialization at class loading time.

While servlets are instantiated as a single instance during Tomcat initialization, both static and non-static fields should be used with caution. They should only be used for immutable or thread-safe data, as they are shared across threads.

### Other controllers
[link](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/CurrenciesController.java#L23)

The controllers seem to contain too much logic. It's better to delegate some of the responsibilities to dedicated service or utility classes. This keeps the controller focused on handling HTTP requests and responses, 

Additionally, I would isolate the validation logic in one place. Centralizing the validation makes the code cleaner, more organized, and reusable across different methods. Currently, the validation is scattered throughout the methods, which makes the code look messy and harder to maintain.

---
The empty methods in the base servlet class can cause issues across all servlets, as they will result in empty pages being returned without any error or explanation. In such an abstraction, it’s better to define a default response, like 'method not supported' or a similar message, to handle these cases properly and provide meaningful feedback to the client.

## ApplicationContextListener
[explicitly loading driver](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/AppContextListener.java#L15)

I can't be sure for 100% but it seems that for contemporary jdbc driver it should be auto-loaded. This code could be removed.

## Recommendations
<b>Key Concepts to Study and Apply:</b>

    Single Responsibility Principle (SRP)
    Dependency Injection (DI) and Singleton Patterns
    Optional for simplifying code and reducing null checks
    Exception Handling best practices for cleaner error management
    Multi-threading and Static Initialization to ensure thread safety
    Separation of Concerns: Split data access, business logic, and validation into distinct layers (DAOs, services, controllers)
    Utility and Service Classes: Use utility classes for repeated tasks and service classes to encapsulate business logic

**Comment by jsteran** [comment]
> ## DAO Layer
> ### 1. ModelMapper Not Declared as Static
> [CurrencyDAO.java Line 17](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L17)
> Fixed in 06b9e3cd32f98772832b0adf465702f51e7409c5
> ### 2. DAO Directly Binding to DTO
> [CurrencyDAO.java Line 59](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L59) 
> Fixed in 2f39b8c9d4c73f3a4d476fc089b04c03ea312f51 
> ### 3. LinkedList Usage
> [CurrencyDAO.java Line 72](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L72) 
> An ArrayList uses a resizable array to store its elements. Therefore, once the underlying array of an ArrayList is full, it must be recreated to accommodate more elements. It should also be noted that within the getAll() method, a LinkedList is preferred for maintaining a list of all currencies, as there is no need for direct access to specific items. For these reasons, a LinkedList was chosen instead of an ArrayList.
> ### 4. Exception Handling
> [CurrencyDAO.java Line 64](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/CurrencyDAO.java#L64) 
> Fixed in 32fe2d3f5d5c1bd5a9d8f62929c8a47594c2fe25
> ### 5. Manual Transaction Management
> [ExchangeRateDAO.java Line 53](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/ExchangeRateDAO.java#L53) 
> Fixed in 54782f81d5c1eb5c6ec2d993227f0d1161b047f3
> ### 6. Service Layer for DAO Interactions
> [ExchangeRateDAO.java Line 57](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/dao/ExchangeRateDAO.java#L57) 
>Fixed in:
> - 54782f81d5c1eb5c6ec2d993227f0d1161b047f3
> - 28b386a3bb445083331b439701be79df3d78d631
> ## Exception
> [DBException.java Line 5](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/exception/DBException.java#L5)
> Fixed in:
> - 32fe2d3f5d5c1bd5a9d8f62929c8a47594c2fe25
> - fbac99ddf0593b93e6c642225c6df93ce01404c1
> ## Service layer
>I will take this into consideration in future versions of my pet projects.
> ## Data source
> [Connection Manager](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/utils/ConnectionManager.java#L10)
> I will take this into consideration in future versions of my pet projects.
> ## Controllers
> ### AbstractMainController
> [Exception Handling](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/AbstractMainController.java#L84)
> Fixed in fbac99ddf0593b93e6c642225c6df93ce01404c1
> [Currency codes initialization](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/AbstractMainController.java#L117) 
> Fixed in 683b752be73bceac01e1f9d13153236541784e38
> ### Other controllers
> [link](https://github.com/anton-kulakov/CurrencyExchange/blob/e4c54457e396dd1fd790b828f07469f26b40d60c/src/main/java/controller/CurrenciesController.java#L23)
> I will take this into consideration in future versions of my pet projects.

**Comment by aleos-dev** [comment]
Great job, Anton! I'm glad that you considered my remarks and provided feedback. 

I want to add a little more on the following matter:

> It should also be noted that within the getAll() method, a LinkedList is preferred for maintaining a list of all currencies, as there is no need for direct access to specific items.

An ArrayList stores its elements in a contiguous block of memory, meaning all elements are located in one area. This allows for better cache locality, making it much faster to iterate over, as all elements can be loaded into memory with minimal overhead.

In contrast, a LinkedList stores its elements as separate nodes scattered throughout memory. This leads to memory fragmentation and poorer cache performance, as the CPU needs to jump between memory locations to retrieve each node. 

So, if we assume we're working with a dataset of 100 (or 1kk) elements and need to access all of them in the getAll() method, using an ArrayList allows us to cache and process them efficiently, while with a LinkedList, it would be like a quest to gather scattered pieces, causing performance degradation.

**Comment by jsteran** [comment]
Aleksei, thank you for your detailed response. This information has changed my perspective on how LinkedList and ArrayList work. I agree that, in this case, using an ArrayList is probably the better option. I've made the necessary changes to the project in 89802a1203b841f8a746e0fcc193bef8aa079d11
